name: GNU/Linux build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build (${{ matrix.cc }} + Qt ${{ matrix.qt }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: clang
            qt: 5
          - cc: gcc
            qt: 6

    env:
      CC: ${{ matrix.cc }}
      QT_MAJOR_VERSION: ${{ matrix.qt }}

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: install dependencies
      run: |
        sudo apt-get update
        if [[ "${QT_MAJOR_VERSION}" == 5 ]]; then
          sudo apt-get install qtbase5-dev
        else
          [[ "${QT_MAJOR_VERSION}" == 6 ]]  # i.e. assert
          sudo apt-get install qt6-base-dev
        fi

    - name: install dependency Clang
      if: "${{ matrix.cc == 'clang' }}"
      run: |-
        sudo apt-get install --yes --no-install-recommends -V clang

    - name: install dependency GCC
      if: "${{ matrix.cc == 'gcc' }}"
      run: |-
        sudo apt-get install --no-install-recommends --yes -V binutils gcc

    - name: install dependency libspnav
      run: |
        git clone --depth 1 https://github.com/FreeSpacenav/libspnav
        cd libspnav
        ./configure
        make
        sudo make install

    - name: configure
      run: |
        set -o pipefail
        ./configure |& tee /dev/stderr | grep -q -F "using Qt ${QT_MAJOR_VERSION}"  # i.e assert use of expected version of Qt

    - name: build
      run: make

    - name: stage install
      run: DESTDIR=spnavcfg-gnulinux make install

    - uses: actions/upload-artifact@v4
      with:
        name: spnavcfg-gnulinux-${{ matrix.cc }}-qt${{ matrix.qt }}
        path: spnavcfg-gnulinux

# vi:ts=2 sts=2 sw=2 expandtab:
